doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Frugu/Migrations'
    # namespace is arbitrary but should be different from Frugu\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations
