easy_admin:
    site_name: '<strong>Frugu</strong> VIP Room'

    formats:
        date: 'd/m/Y'

    design:
        brand_color: '#3B5998'
        templates:
            layout: 'bundles/Admin/layout.html.twig'
        menu:
            - label: 'Auth'
              icon: 'lock'
              children:
                  - { entity: 'User', icon: 'user' }
                  - { entity: 'UserCharacter', icon: 'users' }
            - label: 'Forum'
              icon: 'comments'
              children:
                  - { entity: 'Category', icon: 'tags' }
                  - { entity: 'Conversation', icon: 'comments' }

    entities:
        User:
            label: 'Users'
            class: Frugu\Entity\Auth\User
            list:
                fields:
                    - 'username'
                    - { property: 'isAdmin', label: 'Admin role', sortable: false }
                    - { property: 'createdAt', label: 'Created At'}
                    - { property: 'updatedAt', label: 'Last Update'}

        UserCharacter:
            label: 'Characters'
            class: Frugu\Entity\Auth\UserCharacter
            disabled_actions: ['new', 'edit']
            list:
                fields:
                    - { property: 'characterId', label: 'EvE Character ID', type: 'raw' }
                    - { property: 'characterName', label: 'EvE Character Name' }
                    - { property: 'main', label: 'Main Character', sortable: false }
                    - { property: 'user', label: 'Linked User' }
                    - { property: 'createdAt', label: 'Created At'}
                    - { property: 'updatedAt', label: 'Last Update'}

        Category:
            label: 'Category'
            class: Frugu\Entity\Forum\Category
            list:
                fields:
                    - { property: 'name', label: 'Name'}
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'description', label: 'Description', sortable: false }
                    - { property: 'type', label: 'Type', sortable: false }
                    - { property: 'parent', label: 'Parent' }
                    - { property: 'createdAt', label: 'Created At'}
                    - { property: 'updatedAt', label: 'Last Update'}

        Conversation:
            label: 'Conversation'
            class: Frugu\Entity\Forum\Conversation
            disabled_actions: ['new']
            list:
                fields:
                    - { property: 'name', label: 'Name'}
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'content', label: 'Content', sortable: false }
                    - { property: 'type', label: 'Type', sortable: false }
                    - { property: 'author', label: 'Author' }
                    - { property: 'category', label: 'Category' }
                    - { property: 'parent', label: 'Parent' }
                    - { property: 'createdAt', label: 'Created At'}
                    - { property: 'updatedAt', label: 'Last Update'}
                    - { property: 'deletedAt', label: 'Deleted At'}