easy_admin:
    site_name: '<strong>Frugu</strong> VIP Room'

    formats:
        date: 'd/m/Y'

    design:
        brand_color: '#3B5998'
        menu:
            - { entity: 'User', icon: 'user' }
            - { entity: 'UserCharacter', icon: 'users' }

    entities:
        User:
            label: 'Users'
            class: App\Entity\Auth\User
            list:
                fields:
                    - 'username'
                    - { property: 'isAdmin', label: 'Admin role', sortable: false }
                    - { property: 'createdAt', label: 'Created At'}
                    - { property: 'updatedAt', label: 'Last Update'}

        UserCharacter:
            label: 'Characters'
            class: App\Entity\Auth\UserCharacter
            disabled_actions: ['new', 'edit']
            list:
                fields:
                    - { property: 'characterId', label: 'EvE Character ID', type: 'raw' }
                    - { property: 'characterName', label: 'EvE Character Name' }
                    - { property: 'main', label: 'Main Character', sortable: false }
                    - { property: 'user', label: 'Linked User' }
                    - { property: 'createdAt', label: 'Created At'}
                    - { property: 'updatedAt', label: 'Last Update'}