hwi_oauth:
  firewall_names: ["secured_area"]

  resource_owners:
    eve_online:
      type: "eve_online"
      client_id: "%env(resolve:OAUTH_CLIENT_ID)%"
      client_secret: "%env(resolve:OAUTH_CLIENT_SECRET)%"
      options:
        csrf: true