hwi_oauth:
  firewall_names: ["secured_area"]

  resource_owners:
    eve_online:
      type: "eve_online"
      client_id: "%env(resolve:OAUTH_CLIENT_ID)%"
      client_secret: "%env(resolve:OAUTH_CLIENT_SECRET)%"
      authorization_url: "https://login.eveonline.com/oauth/authorize"
      access_token_url: "https://login.eveonline.com/oauth/token"
      infos_url: "https://login.eveonline.com/oauth/verify"
      options:
        csrf: true