hwi_oauth:
  firewall_names: ["secured_area"]

  resource_owners:
    eve_online:
      type: "eve_online"
      client_id: "2f0f715ecbb84edd856442addfc87e47"
      client_secret: "lDsHdNhYEpyqR4K67gepxVuFdVc0hsgwZ8pZmk84"
      authorization_url: "https://login.eveonline.com/oauth/authorize"
      access_token_url: "https://login.eveonline.com/oauth/token"
      infos_url: "https://login.eveonline.com/oauth/verify"
      options:
        csrf: true