# docker-compose.yml
version: '2'

services:
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        volumes:
            - ./.data/db:/var/lib/postgresql/data:cached
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
    redis:
        image: redis:alpine
        ports:
            - 4852:6379
    php:
        build: docker/php-fpm
        ports:
            - 9000:9000
        links:
            - db:sqldb
            - redis
        volumes:
            - ./:/var/www/symfony:cached
            - ./var/log/docker/symfony:/var/www/symfony/var/log/php-fpm
    nginx:
        build: docker/nginx
        ports:
            - 4850:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./var/log/docker/nginx/:/var/log/nginx