# docker-compose.yml
version: '2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - ./.data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: frugu
    redis:
        image: redis:alpine
        ports:
            - 4852:6379
    php:
        build: docker/php-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
            - redis
        volumes:
            - ./:/var/www/symfony
            - ./var/log/docker/symfony:/var/www/symfony/var/log/php-fpm
    nginx:
        build: docker/nginx
        ports:
            - 4850:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./var/log/docker/nginx/:/var/log/nginx